### ISSUE TITLE
Cypress中測資與upload.js中不同

### ISSUE THREAD

**Issue by LiSeng0903** [ntuee-web-programming/111-1_WebProgramming-Hack3_QA#13]
Sypress中測資與upload.js中不同，數量也不同，請問我是有哪步做錯了嗎

**Comment by Ablabla0403** [comment]
這是正常的 我們cypress會重放資料 原本的upload只是給大家測試而已

**Comment by ericcwlin** [comment]
我自己是在 mongoose.connect 時有設置參數 更改 DB 的名字
但這好像會導致 cypress 讀不到？
至少我後來拿掉參數後用預設的名字就過了，供參
