### ISSUE TITLE
TODO4 coding 範圍

### ISSUE THREAD

**Issue by zih-ya** [ntuee-web-programming/111-1_WebProgramming-Hack3_QA#14]
第四題的敘述提到“Something is lost in the handleSubmitEdit function, you should add them back to finish the update function.” 但// TODO4 和//TODO end的範圍只框在variables裏面，想問這題寫的範圍是可以在那兩個comments之外的嗎？

**Comment by Ablabla0403** [comment]
只需要更改variables就可以了

**Comment by zih-ya** [comment]
OK 了解
