### ISSUE TITLE
2.2的要求

### ISSUE THREAD

**Issue by unicornunicorn** [ntuee-web-programming/111-1_WebProgramming-Hack3_QA#15]
我TODO2.2中，我的畫面有正常顯示從後端用usequery抓回來的items，但gradescope並未通過，請問除了正常顯示items，我還需要做到甚麼才能拿到這部分的分數呢？

**Comment by Ablabla0403** [comment]
請看TODO2-2提示，可能會有時間差的問題

**Comment by ric2k1** [comment]
請看別的 issue

**Comment by lhy1019** [comment]
請問我2-2照著別的component做了但還是過不了是因為什麼原因?

**Comment by linyuting0612** [comment]
同問
