### ISSUE TITLE
第4題cypress過了但Gradescope沒過

### ISSUE THREAD

**Issue by XXXaBg3619** [ntuee-web-programming/111-1_WebProgramming-Hack3_QA#16]
這次是真的惹，做了好多次都沒過
如圖
![截圖 2022-12-20 上午10 59 54](https://user-images.githubusercontent.com/71827144/208571603-fabd171d-4b9d-4eeb-a33e-598c544b7d5c.png)
![截圖 2022-12-20 上午11 00 01](https://user-images.githubusercontent.com/71827144/208571607-df14aa4c-6f0b-4070-8529-3889fee05fce.png)

**Comment by madmaxieee** [comment]
private 除了檢查名字還會檢查其他地方，請仔細看 spec 的要求

**Comment by XXXaBg3619** [comment]
以解決，謝謝
