### ISSUE TITLE
5.1 填了題目要求的東西 但報錯

### ISSUE THREAD

**Issue by Aaron-Hsieh-0129** [ntuee-web-programming/111-1_WebProgramming-Hack3_QA#18]
![截圖 2022-12-20 上午11 24 17](https://user-images.githubusercontent.com/59785770/208574280-0e9d28c1-60b0-4b9c-b6d3-d8edd2e070a5.png)

**Comment by madmaxieee** [comment]
這是語法錯誤喔

**Comment by Aaron-Hsieh-0129** [comment]
!!!我發現了 我耍白痴抱歉QQ
