### ISSUE TITLE
subscription報錯socket closed with event 4500

### ISSUE THREAD

**Issue by timski0428** [ntuee-web-programming/111-1_WebProgramming-Hack3_QA#19]
![image](https://user-images.githubusercontent.com/84845841/208574996-295d2b49-3fd5-43ab-912d-76be4b3d876c.png)
照Home.js的兩個useEffect寫
document後面放UPDATE跟CREATE都不會報錯喚回DELETE就顯示socketclosed

**Comment by madmaxieee** [comment]
你的code有推 github嗎？幫你我看一下
我目前猜是你送的東西格式錯了

**Comment by timski0428** [comment]
推了><

**Comment by madmaxieee** [comment]
確實是你送給後端的東西有錯 再檢查一下喔
