### ISSUE TITLE
無法執行cypress -- Can't run because no spec files were found.

### ISSUE THREAD

**Issue by XXXaBg3619** [ntuee-web-programming/111-1_WebProgramming-Hack3_QA#2]
在hack3下打yarn test後，報錯：
yarn run v1.22.19
$ npx cypress run --spec cypress/e2e/**/*.cy.js
Can't run because no spec files were found.

We searched for any files matching this glob pattern:

cypress/e2e/**/*.cy.js
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Ablabla0403** [comment]
同學 你的cypress資料夾底下有東西嗎？

**Comment by ric2k1** [comment]
可以直接把 hack3/package.json 裡頭的 test 改成：

"test": "npx cypress run --spec cypress/e2e/public-spec.cy.js"

**Comment by XXXaBg3619** [comment]
我重新做一個hack3檔案就能跑了，感謝
