### ISSUE TITLE
Gradescope無法submit

### ISSUE THREAD

**Issue by linyuting0612** [ntuee-web-programming/111-1_WebProgramming-Hack3_QA#20]
無法把檔案加到submission的畫面
(會一直卡在Drag & Drop那邊)

**Comment by dlion168** [comment]
我也有遇到相同問題，用git archive會把我整個wp1111目錄下的所有檔案(hw1-hw9、hack1-hack3)都包進壓縮檔中，導致上傳失敗

**Comment by madmaxieee** [comment]
請注意看完整的指令喔
是 git archive -o hack3.zip HEAD:hack3

**Comment by madmaxieee** [comment]
啊卡住那個可以進 meet 嗎 https://meet.google.com/edx-tfpt-vsb

**Comment by linyuting0612** [comment]
我解決了
感謝

**Comment by ric2k1** [comment]
可以分享是什麼原因嗎？

**Comment by linyuting0612** [comment]
我也不知道
重新壓縮一次就可以交出去了
