### ISSUE TITLE
臨時無法gitpush 進而無法 git archive

### ISSUE THREAD

**Issue by xiguaakako** [ntuee-web-programming/111-1_WebProgramming-Hack3_QA#21]
![image](https://user-images.githubusercontent.com/96676117/208576189-78157e14-993f-451c-8e24-53964494ac96.png)
git push時臨時出現以下問題

請問有辦法手動壓縮嗎 這樣也上傳不了gradescope

**Comment by madmaxieee** [comment]
不用 push 也可以用 git archive 壓縮喔
只要有 commit 就好

**Comment by xiguaakako** [comment]
成功了 謝謝
那請問最終繳交至github有替代方式嗎

**Comment by madmaxieee** [comment]
github 去年開始就不能用密碼了，要設定 token 或是用 ssh 才可以 authenticate

**Comment by xiguaakako** [comment]
> 成功了 謝謝 那請問最終繳交至github有替代方式嗎

想請問這個
我可能無法git push

**Comment by madmaxieee** [comment]
可以去 google 一下怎麼用 ssh 去authenticate github
