### ISSUE TITLE
6-5 Subscription 報錯

### ISSUE THREAD

**Issue by liangyu0516** [ntuee-web-programming/111-1_WebProgramming-Hack3_QA#22]
請問助教，我照著 TODO 6 的步驟進行，但在 6-5 照著 Home.js 裡面的兩個 subscripotions 的寫法還是錯，想請問是否有漏掉的部分，前後端錯誤訊息如附圖：
![image](https://user-images.githubusercontent.com/58724609/208575495-76ba6f4c-128e-4747-932c-55202bc3ddfb.png)
![image](https://user-images.githubusercontent.com/58724609/208575559-6d288aa1-0711-4517-a922-d4b228f5b1a8.png)

**Comment by madmaxieee** [comment]
前面有個地方寫錯了喔

**Comment by Ablabla0403** [comment]
看起來像是你前端有東西沒有送對，請確定前面步驟皆有成功

**Comment by liangyu0516** [comment]
好的我再檢查一下，謝謝助教們
