### ISSUE TITLE
ubuntu死掉環境問題 想請求延時

### ISSUE THREAD

**Issue by xiguaakako** [ntuee-web-programming/111-1_WebProgramming-Hack3_QA#27]
![image](https://user-images.githubusercontent.com/96676117/208579827-272896e9-80d2-41bb-86ef-7b51c9ba9977.png)
助教您好，想請問如上的環境問題有可以有機會延時嗎
現在連壓縮檔都做不出來...我已經半小時卡在這裡了

**Comment by ric2k1** [comment]
那你至少先 push 到 GitHub 吧，我們事後再手動批改

**Comment by xiguaakako** [comment]
我上一篇有發issue，我現在git push也不能用了...
助教請我自行google，可是我真的沒時間了

**Comment by Ablabla0403** [comment]
你能用其他方法壓縮上傳嗎

**Comment by xiguaakako** [comment]
剛剛push終於修好，現在已經上傳上去了
請問手動批改會是跟gradescope取高分的那一邊嗎 我好怕分數掉光...

**Comment by ric2k1** [comment]
你 gradescope 可以 submit 嗎？

**Comment by xiguaakako** [comment]
他開著
請問現在是可以submit的狀態嗎
