### ISSUE TITLE
手動壓縮hack3方法

### ISSUE THREAD

**Issue by dupeicih** [ntuee-web-programming/111-1_WebProgramming-Hack3_QA#4]
助教您好：

想請問如果沒有 git add, git commit，或 commit message 不是 hack3 的話，可以使用  git archive -o hack3.zip HEAD:hack3 嗎？
另外想請問有沒有手動壓縮的方法？

謝謝！

**Comment by Ablabla0403** [comment]
照著我們的步驟操作就可以正常壓縮了 還是你有遇到什麼錯誤訊息
