### ISSUE TITLE
1-1問題

### ISSUE THREAD

**Issue by kuo220** [ntuee-web-programming/111-1_WebProgramming-Hack3_QA#8]
<img width="804" alt="截圖 2022-12-20 上午9 59 26" src="https://user-images.githubusercontent.com/80812831/208563834-47edd5db-2264-444d-91e9-2369e6975fb2.png">

不知道為何畫面還是error

**Comment by ric2k1** [comment]
你有把 code 推到 GitHub 嗎？

**Comment by Ablabla0403** [comment]
請確定mongo有正確連上

**Comment by kuo220** [comment]
有推上了
mongo有連上 grapescope也有拿到分
